### ISSUE TITLE
Error on launch [object Object]

### ISSUE THREAD

**Issue by matthieu526** [localmed/api-mock#54]
Hi,

When I launch api-mock, I have the following error :
<img width="776" alt="screen shot 2016-10-21 at 14 03 03" src="https://cloud.githubusercontent.com/assets/6515004/19597808/28a039a0-9797-11e6-8716-85b031c9c94a.png">

Do you have any idea about what it means ?
Thanks in advance.

**Comment by rossettewuyu** [comment]
the carriage return key is different on windows and linux. it is "\n\r" on windows and which is "\n" on linux.
try format your *.md file for the different system. 
if you edit the .md file on windows and run api-mock on linux, run commad in shell like:
sed -e "s/.$//" your.md >> new.md
on the other side, you edit the .md file on linux and run api-mock on windows, run command is shell like:
sed -e "s/$/\r/" your.md >> new.md

**Comment by matthieu526** [comment]
In fact, the problem was a between spaces and tabulations. It seems that it does not support "\t".
